version: '3.7'
services:
  database:
    image: postgres:12.1-alpine
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    ports:
      - $DB_HOST:$DB_PORT:5432
    volumes:
      - ./tmp/postgresql:/var/lib/postgresql/data
    env_file:
      - .env
